version: '3.9'

networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
      
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-common-keys-apps: &common-keys-apps
  networks:
    - npm_proxy
 # working_dir:
 #   - $APPDATADIR
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
 # working_dir:
 #   - $APPDATADIR
  security_opt:
    - privileges:true
  restart: unless-stopped

services:
# https://github.com/NginxProxyManager/nginx-proxy-manager/blob/docker-user-group/docker/docker-compose.dev.yml
#link to npm
  npm:
    <<: *common-keys-apps
    container_name: npm_core
    image: jc21/nginx-proxy-manager:v3
    ports:
      - 3080:80
      - 3081:81
      - 3443:443
    volumes:
      - $APPDATADIR/npm_data:/data
      - $APPDATADIR/le_data:/etc/letsencrypt
      # Need to check setting
      #- ../backend:/app
      #- ../frontend:/app/frontend
      #- ../global:/app/global
    environment:
      <<: *default-tz-puid-pgid
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'npm'
      DB_MYSQL_NAME: 'npm'
      #DB_SQLITE_FILE: '/config/database.sqlite'
      DISABLE_IPV6: 'true'
    depends_on:
      - db
   # NEED TO CHECK THIS SETTING.
   # working_dir: $APPDATADIR
  db:
    <<: *common-keys-apps
    image: jc21/mariadb-aria
    container_name: npm_db
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - $APPDATADIR/db_data:/var/lib/mysql
  portainer:
    <<: *common-keys-core
    image: portainer/portainer
    volumes:
      - $APPDATADIR/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  radarr:
    <<: *common-keys-apps
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - $APPDATADIR/radarr:/config
      - $MOVIEDIR:/movies
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK: '022'
  sonarr:
    <<: *common-keys-apps
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  bazarr:
    <<: *common-keys-apps
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $MOVIEDIR:/movies
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  jackett:
    <<: *common-keys-apps
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - 9117:9117
    volumes:
      - $APPDATADIR/jackett:/config
    environment:
      <<: *default-tz-puid-pgid
      AUTO_UPDATE: 'true' #optional
      RUN_OPTS: '' #optional
      UMASK: '022'
  deluge:
    <<: *common-keys-apps
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $APPDATADIR/deluge:/config
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
      DELUGE_LOGLEVEL: 'error' #optional
volumes:
  npm_data:
    name: npm_data
  le_data:
    name: npm_le_data
  db_data:
    name: npm_db_data
