version: '3.9'

networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
      
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-common-keys-apps: &common-keys-apps
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

services:

  npm:
    <<: *common-keys-apps
    container_name: npm
    image: jc21/nginx-proxy-manager:v3
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - $APPDATADIR/npm:/data
      - $APPDATADIR/letsencrypt:/etc/letsencrypt
    environment:
      <<: *default-tz-puid-pgid
      DB_SQLITE_FILE: '/config/database.sqlite'
      DISABLE_IPV6: 'true'
  radarr:
    <<: *common-keys-apps
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - $APPDATADIR/radarr:/config
      - $MOVIEDIR:/movies
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK: '022'
  sonarr:
    <<: *common-keys-apps
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  bazarr:
    <<: *common-keys-apps
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $MOVIEDIR:/movies
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  jackett:
    <<: *common-keys-apps
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - 9117:9117
    volumes:
      - $APPDATADIR/jackett:/config
    environment:
      <<: *default-tz-puid-pgid
      AUTO_UPDATE: 'true' #optional
      RUN_OPTS: '' #optional
      UMASK: '022'
  deluge:
    <<: *common-keys-apps
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $APPDATADIR/deluge:/config
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
      DELUGE_LOGLEVEL: 'error' #optional
