version: '3.9'

secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  DB_ROOT_PWD:
    file: ./secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: ./secrets/mysql_pwd.txt
  PLEX_CLAIM:
    file: ./secrets/plex_claim.txt
    
networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
      
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-common-keys-apps: &common-keys-apps
  networks:
    - npm_proxy
 # working_dir:
 #   - $APPDATADIR
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
 # working_dir:
 #   - $APPDATADIR
  security_opt:
    - privileges:true
  restart: unless-stopped

services:
# https://github.com/NginxProxyManager/nginx-proxy-manager/blob/docker-user-group/docker/docker-compose.dev.yml
#link to npm
  npm:
    <<: *common-keys-apps
    container_name: npm
    image: jc21/nginx-proxy-manager:v3
    ports:
      # Public HTTP Port:
      - 3080:80
      # Public HTTPS Port:
      - 3081:81
      # Admin Web Port:
      - 3443:443
    volumes:
      - $APPDATADIR/npm_data:/data
      - $APPDATADIR/le_data:/etc/letsencrypt
      # Need to check setting
      #- ../backend:/app
      #- ../frontend:/app/frontend
      #- ../global:/app/global
    environment:
      <<: *default-tz-puid-pgid
      # These are the settings to access your db
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'npm'
      # DB_MYSQL_PASSWORD: "npm"  # use secret instead
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      DB_MYSQL_NAME: 'npm'
      #DB_SQLITE_FILE: '/config/database.sqlite
      # If you would rather use Sqlite, remove all DB_MYSQL_* lines above
      # comment this if IPv6 is enabled on your host
      DISABLE_IPV6: 'true'
      X_FRAME_OPTIONS: "sameorigin"
    secrets:
      - MYSQL_PWD
    depends_on:
      - db
   # NEED TO CHECK THIS SETTING.
   # working_dir: $APPDATADIR
  db:
    <<: *common-keys-apps
    image: jc21/mariadb-aria
    container_name: npm_db
    ports:
      - 33306:3306
    environment:
      # MYSQL_ROOT_PASSWORD: "npm"  # use secret instead
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - $APPDATADIR/db_data:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
      
  portainer:
    <<: *common-keys-core
    image: portainer/portainer
    Port:
      - 9443:9443
    volumes:
      - $APPDATADIR/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *default-tz-puid-pgid
  radarr:
    <<: *common-keys-apps
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - $APPDATADIR/radarr:/config
      - $MOVIEDIR:/movies
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK: '022'
  sonarr:
    <<: *common-keys-apps
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  bazarr:
    <<: *common-keys-apps
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - $APPDATADIR/sonarr:/config
      - $TVDIR:/tv
      - $MOVIEDIR:/movies
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
  jackett:
    <<: *common-keys-apps
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - 9117:9117
    volumes:
      - $APPDATADIR/jackett:/config
    environment:
      <<: *default-tz-puid-pgid
      AUTO_UPDATE: 'true' #optional
      RUN_OPTS: '' #optional
      UMASK: '022'
  deluge:
    <<: *common-keys-apps
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $APPDATADIR/deluge:/config
      - $DOWNLOADDIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: '022' #optional
      DELUGE_LOGLEVEL: 'error' #optional
  plex:
    <<: *common-keys-apps
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    port:
      - 32400:32400
    volumes:
      - $APPDATADIR/plex:/config
      - $TVDIR:/tv
      - $MOVIEDIR:/movies
    environment:
      <<: *default-tz-puid-pgid
      VERSION: 'latest'
      HOSTNAME: '$PLEX_HOSTNAME'
      PLEX_CLAIM: '$PLEX_CLAIM'
      PLEX_CLAIM_PASSWORD__FILE: /run/secrets/PLEX_CLAIM
      PLEX_UID: '$PUID'
      PLEX_GID: '$PGID'
      
volumes:
  npm_data:
    name: npm_data
  le_data:
    name: npm_le_data
  db_data:
    name: npm_db_data
  portainer_data:
    name: portainer_data
